apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
   color: red
  name: mydep1
spec:
  replicas: 10
  selector:
    matchLabels:
     color: red
  template:
    metadata:
      labels:
       color: red
    spec:
      containers:
      - image: nginx
        name: akc
        ports:
        - containerPort: 80
