apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: ak1
  name: ak1
spec:
  containers:
  - image: httpd
    name: ak1con
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
