apiVersion: v1
kind: ReplicationController
metadata:
  name: ak-rc
spec:
 replicas: 5
 template:
    metadata:
      labels:
        web: xyz
    spec:
      containers:
      - name: akc1
        image: nginx
        ports:
        - containerPort: 80